services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: patientdb
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build: .
    container_name: patient-microservice
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/patientdb

  test:
    build:
      context: .
      target: tester
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/patientdb
    volumes:
      - maven_cache:/root/.m2

volumes:
  mongo_data:
  maven_cache: