spring.application.name=patient-microservice
server.port=8080

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Logging
logging.level.org.example.patientmicroservice.model.patient=INFO
logging.level.org.springframework.data.mongodb=WARN
